name: essential
description: "studying essential concepts in Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  json_annotation: ^4.9.0
  http: ^1.2.2
  dio: ^5.7.0
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/2x/
     - assets/images/3x/
     - assets/text/
